config/routes.rb
Rails.application.routes.draw do

  get 'points/new'

  resources :restaurants
  resources :maps
  resources :points

  resources :microcomments, only: [:create, :destroy]

  root  'static_pages#home'

  match '/help',            to: 'static_pages#help',          via: 'get'
  match '/map1',            to: 'static_pages#map1',          via: 'get'
  match '/map2',            to: 'static_pages#map2',          via: 'get'
  match '/map3',            to: 'static_pages#map3',          via: 'get'

  match '/test',            to: 'static_pages#test',          via: 'get'

  match '/restaurants/:id/edit',  to: 'restaurants#edit',   via: 'put'
  match '/maps/:id/edit',  to: 'maps#edit',   via: 'put'

  match '/maps/1',  to: 'maps#show',   via: 'put'

end

app/models/bak_restaurant.rb
# jr@oblique:  10/9/14


class Restaurant < ActiveRecord::Base

	# Validation block 
  	validates :name,  presence: true, length: { maximum: 50 } 
  	validates :info,  presence: true, length: { maximum: 50 } 
  	validates :lat_dec,  presence: true, length: { maximum: 50 } 
  	validates :long_dec,  presence: true, length: { maximum: 50 } 

  	# email: using a regular expression to validate format 
  	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	#validates :email, 
  	#		presence: true, 
  	#		format: { with: VALID_EMAIL_REGEX },
    #       uniqueness: { case_sensitive: false }

  	#has_secure_password
  	#validates :password, length: { minimum: 6 } 



end

app/controllers/bak_restaurants_controller.rb
class RestaurantsController < ApplicationController


  def destroy
    Restaurant.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to restaurants_url
  end



  def index
    #@restaurants = Restaurant.all
    #@restaurants = Restaurant.paginate(page: params[:page])
    #@restaurants = Restaurant.all.group_by{|u| u.name}

    @restaurants = Restaurant.order(:name).paginate(page: params[:page])
  end


  def edit
    @restaurant = Restaurant.find(params[:id])
  end


  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      flash[:success] = "Profile updated"
      redirect_to @restaurant
    else
      render 'edit'
    end
  end





  def show
    @restaurant = Restaurant.find(params[:id])
  end
 

  def new
  	@restaurant = Restaurant.new
  end


  def create
  	@restaurant = Restaurant.new(restaurant_params)
    
    if @restaurant.save
      #sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      #redirect_to @user
    else
      render 'new'
    end
  end



  private
  
    def restaurant_params
      #params.require(:restaurant).permit(:name, :info, :lat_dec, :long_dec)
      params.require(:restaurant).permit(:id, :name, :info, :lat_dec, :long_dec)
    end

end

app/views/bak_restaurants/_restaurant.html.erb
<li>
  <%#= gravatar_for user, size: 52 %>

  <%#= link_to user.name, user %>
  <%= link_to restaurant.name, restaurant %>
      | 
  <%= restaurant.info %>,

  <%= restaurant.lat_dec %>,

  <%= restaurant.long_dec %>

  <%# if current_user.admin? && !current_user?(user) %>

    | 
      <%#= link_to "edit", restaurant, method: :edit %>
      <%#= link_to("Answered", restaurant_path(:restaurant, :status => true), :method => :put) %>

      <%= link_to 'Edit', {:action => :edit, :id => restaurant.id}, :method => :put %>
    | <%= link_to "Delete", restaurant, method: :delete,
        data: { confirm: "You sure?" } %>

  <%# end %>

</li>

app/views/bak_restaurants/create.html.erb
<% provide(:title, 'Create Restaurant') %>

<h1>Create Restaurant</h1>


<div class="row">
  <div class="span6 offset3">

    <%= @restaurant.name %> ,
    <%= @restaurant.info %>,
    <%= @restaurant.lat_dec %>,
    <%= @restaurant.long_dec %>

  </div>
</div>

app/views/bak_restaurants/edit.html.erb
<% provide(:title, "Edit restaurant") %>

<h1>Update your data</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(@restaurant) do |f| %>

      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :info %>
      <%= f.text_field :info %>

      <%= f.label :lat_dec %>
      <%= f.text_field :lat_dec %>

      <%= f.label :long_dec %>
      <%= f.text_field :long_dec %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/bak_restaurants/index.html.erb
<% provide(:title, 'Index of Restaurants') %>

<h1>Index of Restaurants</h1>

<%= will_paginate %>


<ul class="users">
  
  <%= render @restaurants %>

<%# @restaurants.keys.sort.each do |restaurant| %>
    <%#= starting_letter %>
    <%# @restaurants[starting_letter].each do |restaurant| %>

    <%#= restaurant %>
  	<%#= render @restaurant %>

  <%# end %>
<%# end %>

</ul>


<%= will_paginate %>

app/views/bak_restaurants/new.html.erb
<% provide(:title, 'New Restaurant') %>

<h1>New Restaurant</h1>


<div class="row">
  <div class="span6 offset3">

    <%#= @map.name %>, <%#= @map.file_name %>


    <%= form_for(@restaurant) do |f| %>
      
      <%= f.label :name,                  "Name" %>
      <%= f.text_field :name %>
      
      <%= f.label :info,                  "Info" %>
      <%= f.text_field :info %>
      
      <%= f.label :lat_dec,                  "Lat decimal" %>
      <%= f.text_field :lat_dec %>
      
      <%= f.label :lng_dec,                  "Long decimal" %>
      <%= f.text_field :lng_dec %>
      


      <%#= f.label :file_name,              "File name" %>
      <%#= f.text_field :file_name %>

      <%#= f.label :type,                 "Type" %>
      <%#= f.text_field :type %>


      <%= f.submit "Create restaurant", class: "btn btn-large btn-primary" %>
    <% end %>
    

  </div>
</div>

app/views/bak_restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>

<h1>Show restaurant</h1>



<div class="row">

  <aside class="span4">

    <section>

      <h1>
        <%#= gravatar_for @user %>
        <%= @restaurant.name %>, 
        <%= @restaurant.info %>, 
        <%= @restaurant.lat_dec %>, 
        <%= @restaurant.long_dec %>
      </h1>

    </section>

  </aside>
</div>