config/routes.rb
Rails.application.routes.draw do

  get 'points/new'

  resources :restaurants
  resources :maps
  resources :points

  resources :microcomments, only: [:create, :destroy]

  root  'static_pages#home'

  match '/help',            to: 'static_pages#help',          via: 'get'
  match '/map1',            to: 'static_pages#map1',          via: 'get'
  match '/map2',            to: 'static_pages#map2',          via: 'get'
  match '/map3',            to: 'static_pages#map3',          via: 'get'

  match '/test',            to: 'static_pages#test',          via: 'get'

  match '/restaurants/:id/edit',  to: 'restaurants#edit',   via: 'put'
  match '/maps/:id/edit',  to: 'maps#edit',   via: 'put'

  match '/maps/1',  to: 'maps#show',   via: 'put'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Template</a>
    by Javier Revilla
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--

<header class="navbar navbar-fixed-top navbar-inverse">
-->

<header class="navbar navbar-fixed-top">

<!--
  <div class="navbar-inner">
-->

    <div class="container">

      <%#= link_to "test maps", '#', id: "logo" %>
      <%= link_to "viva  lima", '#', id: "logo" %>

      <nav>
        <ul class="nav pull-right">


          <li><%= link_to "Home",     root_path %></li>
          <li><%#= link_to "Help",     help_path %></li>

          <li><%#= link_to "",      _path  %></li>

          <li><%= link_to "New Map",      new_map_path  %></li>
          <li><%= link_to "Maps",        maps_path  %></li>

          <li><%= link_to "Places",        restaurants_path  %></li>
          <li><%#= link_to "Points",        points_path  %></li>


          <li><%#= link_to "R New",         new_restaurant_path  %></li>
          <li><%#= link_to "R Index",       restaurants_path  %></li>

          <li><%#= link_to "P New",         new_point_path  %></li>
          <li><%#= link_to "P Index",       points_path  %></li>

          <li><%#= link_to "Map 1",      map1_path  %></li>
          <li><%#= link_to "Map 2",      map2_path  %></li>
          <li><%#= link_to "Map 3",      map3_path  %></li>

        </ul>
      </nav>
    </div>
<!--
  </div>
-->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= include_gon %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>

    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


    <style>
      table, th, td {
        /*
        border: 1px solid black;
        border-collapse: collapse;
        */     
      }
      th, td {
        padding: 5px;
      }
      th {
        text-align: left;
      }
    </style>

  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class="container">


     <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
   

      <%= yield %>
      <%#= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

    </div>
  </body>

</html>